---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  synced_folders:
    - ["./", "/ec-loadtest"]
  network:
    - ["private_network", {ip: "33.33.33.12"}]
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ec-loadtest::default]
    attributes:
